version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_stayspot
    image: mongo:latest 
    restart: always
    volumes: 
      - mongo_data:/data/db 

  # Node API service
  api:
    build: .
    context: .
    dockerfile: /full/path/to/Dockerfile
    ports: 
      - "4000:4000"  # Map container port to host port
    environment:
      NODEMAILERPASSWORD: "fsfuqhgrrlsmigjv"
      NODEMAILER_EMAIL: "jamshadalij2004@gmail.com"
      STRIPE_SECERET_KEY: "sk_test_51NbSNASISA5Tam1zrEocL4EIZxaWjowsNcYgPkOvoNviE5drZ5ak6zzfT1Wj5eJY1nxoeLVOMCdh2bWk7tS5uYz200XAUFwjGA"
      STRIPE_KEY_ID: "rzp_test_3qgmRXzHbaIU3G"
      STRIPE_KEY_SECERET: "dkYqSUoji4OpW4vSoOPraomb"
      TOKEN_SECERET_KEY: "00f3f20c9fc43a29d4c9b6b3c2a3e18918f0b23a379c152b577ceda3256f3ffa"
      CLOUDINARY_NAME: "dwf41qfxv"
      CLOUDINARY_API_KEY: "251486947687782"
      CLOUDINARY_API_SECRET: "fMytGYObh2e8zjrUvJffJ6x698k"
      # ORIGIN: "http://localhost:3000"
      MONGO_DB_URL: "mongodb://localhost:27017/stayspot"
    depends_on:
      - mongo_db


volumes:
  mongo_data:
