version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_stayspot
    image: mongo:latest 
    restart: always
    volumes: 
      - mongo_data:/data/db 

  # Node API service
  api:
    build:
      context: .
    ports: 
      - "4000:4000"  # Map container port to host port

volumes:
  mongo_data:
